### ISSUE TITLE
Dodanie podstrony poświęconej rekrutacji

### ISSUE THREAD

**Issue by pktiuk** [KNR-PW/knr-pw.github.io#16]
Trzeba będzie też zrobić jakąś stronę poświęconą rekrutacji.

- Dodanie zakładki rekrutacji do menu górnego
- Dodanie jakiejś prostej templatki dla pustej strony w razie, gdybyśmy chcieli potem sami jeszcze napisać inną stronę tego typu. (taka prosta templatka do pisania artykułów, pewnie wystarczy skopiować templatkę dla projektu, zmienić jej nazwę na `article` i troche uprościć)
- Dodanie samej strony o rekrutacji
- opisanie nowych rzeczy w readme
- napisanie o samej rekrutacji (zlecimy to komuś z PRu)

**Comment by pktiuk** [comment]
@DominikChmielak Kiedy ustalimy dokładny przebieg rekrutacji trzeba będzie to opisać tutaj.

**Comment by AdamGetBackToWork** [comment]
@pktiuk ja moge sie sprobowac tym zajac, pewnie w przyszlym tygodniu tho... 
@DominikChmielak  wrzuć tu tą prezentację

**Comment by DominikChmielak** [comment]
https://wutwaw.sharepoint.com/:p:/s/KNR-ZarzdiAdministracja/EdrnlRH9BCtLkpnxzHA4dwMBv_lnqyQEHSXRFBNJ6UPA0g?e=2DltET

opis rekrutacji
https://nextcloud.knr.edu.pl/apps/collectives/Zarz%C4%85d%20i%20Administracja/Ludzie/Rekrutacja%20v2023?fileId=3228

**Comment by AdamGetBackToWork** [comment]
Nie jestem dodany do pierwszej grupy

**Comment by AdamGetBackToWork** [comment]
![screenshot-knr](https://github.com/KNR-PW/knr-pw.github.io/assets/122032124/207b232e-ef2b-45ee-b3c4-545a144a4895)

Co powiecie na coś takiego? Bedzie wembedowane w strone jako stały element. Dałbym tam slajdy z prezki z opisem jakims, datami rekrutacji (na stale poczatek semu kazdego itp) i kontaktem ds. rekrutacji (- mozna by dac jakiegos maila naszego w stylu: knr+rekrutacja@gmail.com wtedy by trafialo do nas na skrzynke wszystko ale do odzielnego folderu(chodzi o zastosowanie tego "+"), no i kodem QR do discorda, ale wtedy trzeba by go jakos zabezpieczyc zgoda moderatora czy cos, i dodatkowo wiadomo jakies takie rzeczy co do glowy przyjdzie zeby tam wrzucic

**Comment by DominikChmielak** [comment]
Imo lepsze będzie odsyłanie do discorda dla rekrutów, tam jest miejsce na pytania. 
Chodzi tutaj o to, że mało osób będzie wchodzić na te maile, a tym bardziej odpisywać, a odpowiedź na DC jest szybsza i bardziej przyzwoita, w końcu i tak nikogo ten dc nie ominie
Kilka slajdów z prezki można dać, ale nie wszystkie.

**Comment by AdamGetBackToWork** [comment]
> No spoko, to kontakt przez dc = kod qr do dc dodać
> Ktore slajdy z prezentacji chcesz by byly? 
> jak reszta tego wszystkiego? Pomysl z ustrukturyzowaniem w projekcie? moze to tak wygladac?

**Comment by pktiuk** [comment]
@AdamGetBackToWork  Można dać kod QR oraz samego linkado kliknięcia, aby było wygodnie ludziom na kompach https://discord.gg/gdT9zM2AmA

**Comment by AdamGetBackToWork** [comment]
Dobra, czyli propozycja struktury:
- naglowek
- krotki opis 
- slajdy z prezentacji (moze z jakimis podpisami)
- daty rekrutacji
- kod QR i link do dc
co sadzicie?

O i od razu pytanie o css, jak w style.css chcesz @pktiuk, bym adresowal nowo wrzucane elementy? pisac na dole w wydzielonej sekcji "RECRUITMENT* wszystko, czy jakos inaczej to strukturyzować?

**Comment by AdamGetBackToWork** [comment]
No wiadomo, bałaganiarzem nie jestem (stad tez te pytania o css'a) :)

**Comment by AdamGetBackToWork** [comment]
Wrzucić tu czy zrobic pr?

**Comment by pktiuk** [comment]
Zrobić PR,  
Spojrzę przed przyklepaniem

**Comment by pktiuk** [comment]
Ale jak będziesz miał inne drobne poprawki to już bez PRa

**Comment by AdamGetBackToWork** [comment]
Ok, to jak skończę to pr, pewnie jeszcze dzisiaj troche pozniej bo mam cos jeszcze do zrobienia :)

I btw, jak się dodaje poprawki bez PR? Chyba coś zielony jestem w tym XD

**Comment by pktiuk** [comment]
Po prostu dodajesz kolejne commity, albo jeszcze lepiej edytujesz sobie commity, aby były ładne, a potem pushujesz z flagą `--force` (wtedy nadpisujesz commity `git push --force`)

**Comment by DominikChmielak** [comment]
W sumie przeszukałem kilka stron w szukaniu inspiracji i niezbyt wiele kół ma to jakoś sensownie ogarnięte. Znalazłem takie, może się przydadzą B)

https://www.scorpio.pwr.edu.pl/rekrutacja/ - no tutaj, to ogólnie zajebiscie ogarnięte 
https://racing-pwr.pl/zostan-czlonkiem/ - fajny zegar xD

Możemy rozegrać to na dwa sposoby 
1. Po prostu ścisłe informacje o rekrutacji, bez zachęcania, tłumaczenia itp. 
2. Styl tłumaczenia wszystkiego, tak jak na spotkaniach rekrutacyjnych
 
- Przede wszystkim widzi mi się graf całego cyklu rekrutacji - od kandydata do członka

a w ramach chęci:
- Benefity z dołączenia do nas
- Fajnie byłoby zobaczyć przykładowe projekty i ich wykonanie, tam jeden w prezce jest już pokazany, z innymi trzeba poszukać


Ogólnie daję tutaj wolną rękę, jak będzie tak będzie, ale żeby miało ręce i nogi oraz nie były wrzucone chamsko 1:1 screeny z prezentacji

No i ładnie zaznaczone w tekście, że kandydatem może być tylko student PW, żeby jakieś randomy nie pisały

**Comment by AdamGetBackToWork** [comment]
A ten graf to przerobic z prezentacji by nie byl taki sam?
tak ze np bedzie w dymku nazwa etapu (np wybranie projektu) a obok ze trzy zdania wiecej a potem strzalka do keljengo etapu i tak z gory na dol, cos w stylu opisu sekcji opisu dzialow z scorpio?

I dodatkowo to to bedzie artykul bardziej nizeli cos interaktywnego, pisane w md, Do takich interaktywnych to bylaby wieksza robta, nie wiem czy jest sens robic z tego taka duza rzecz. Szczegolnie ze sa elementy na stronie/socialach ktore mozna by porozwijac wczesniej

**Comment by pktiuk** [comment]
Z jednej strony fajnie zrobić coś interaktywnego, ale z drugiej to będzie dużo cięższe do utrzymania i wprowadzania zmian. Z tego powodu ja bym preferował formę artykułu

**Comment by DominikChmielak** [comment]
nie no graf, to jak ci wygodnie. Jeżeli masz pomysł, aby opisać to inaczej, to up2u.
Mogę powiedzieć, że tworzenie takich rzeczy w powerpoint, to szybka i łatwa sprawa

Nie może być to też na tyle trudne, żeby prace zajęły kilka miesięcy

**Comment by pktiuk** [comment]
Strona do rekrutacji oraz link do niej już dodany, zamykam.
